#!/usr/bin/env bash
# a Bash script that:
	#Creates the file /var/run/myscript.pid containing its PID
	#Displays To infinity and beyond indefinitely
	#Displays I hate the kill command when receiving a SIGTERM signal
	#Displays Y U no love me?! when receiving a SIGINT signal
	#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# Create the PID file
echo $$ > /var/run/myscript.pid

# Display "To infinity and beyond" indefinitely
while true;
do
	echo "To infinity and beyond"
	sleep 1
done &

# Trap the signals
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid; exit 0" SIGQUIT SIGTERM

# Wait for signals
while true; do
	sleep 1
done

