#!/usr/bin/env bash
#Write a Bash script that displays:
	#To infinity and beyond indefinitely
	#With a sleep 2 in between each iteration
	#I am invincible!!! when receiving a SIGTERM signal
#trap 67-stop_me_if_you_can SIGTERM
sigterm_handler() {
	echo "I am invincible!!!"
	#exit 0
}
trap sigterm_handler SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
	#trap sigterm_handler SIGTERM
done
