#!/usr/bin/env bash
# a Bash script that gives you information about the school file

if [[ ! -e /home/vagrant/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/school ]];
then
	echo "school file does not exist"
else
	echo "school file exists"
	if [ -s school ];
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f school ];
	then
		echo "school is a regular file"
	fi
fi
